### ISSUE TITLE
Creating a calendar

### ISSUE THREAD

**Issue by Dog** [Kotti/kotti_calendar#10]
Creating a calendar (no feed) causes this error
```
ERROR:waitress:Exception when serving /example-calendar/
Traceback (most recent call last):
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/fanstatic/publisher.py", line 219, in __call__
    return self.app(environ, start_response)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/fanstatic/injector.py", line 64, in __call__
    response = request.get_response(self.app)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/webob/request.py", line 1320, in send
    application, catch_exc_info=False)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/webob/request.py", line 1284, in call_application
    app_iter = application(self.environ, start_response)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 92, in tm_tween
    reraise(*exc_info)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 73, in tm_tween
    response = handler(request)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/Users/Dog/portfolio/Kotti/kotti/views/view.py", line 24, in view_content_default
    response = render_view_to_response(context, request, name=view_name)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/pyramid/view.py", line 60, in render_view_to_response
    return view(context, request)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/Users/Dog/.pyenv/versions/kotti/lib/python2.7/site-packages/pyramid/config/views.py", line 491, in _class_view
    response = getattr(inst, attr)()
  File "/Users/Dog/portfolio/Kotti/kotti_calendar/kotti_calendar/views.py", line 248, in view
    self.need()
  File "/Users/Dog/portfolio/Kotti/kotti_calendar/kotti_calendar/views.py", line 135, in need
    fullcalendar_locales["en"].need()
KeyError: 'en'
```

**Comment by disko** [comment]
Fixed in 1eaf3f3bc511e747e81475df714768941a2053f8 (https://pypi.python.org/pypi/kotti_calendar/0.8.2).
