### ISSUE TITLE
js.fullcalendar == 2.3.1 crashes kotti_calendar

### ISSUE THREAD

**Issue by jjmurre** [Kotti/kotti_calendar#11]
Downgrading js.fullcalendar to 2.2.5 solves the problem

Traceback (most recent call last):
  File "local/lib/python2.7/site-packages/waitress/channel.py", line 336, in service
    task.service()
  File "local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "local/lib/python2.7/site-packages/waitress/task.py", line 388, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "local/lib/python2.7/site-packages/fanstatic/publisher.py", line 219, in **call**
    return self.app(environ, start_response)
  File "local/lib/python2.7/site-packages/fanstatic/injector.py", line 76, in **call**
    result = self.injector(response.body, needed, request, response)
  File "local/lib/python2.7/site-packages/fanstatic/injector.py", line 180, in **call**
    compat.as_bytestring('%s</head>' % top.render()), 1)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4117: ordinal not in range(128)

So "js.fullcalendar" gives back unicode strings crashing fanstatic.

**Comment by tonthon** [comment]
it comes from the use of string formatting with normal string that is used in fanstatic.
Since recent versions js.fullcalendar declares Ressources with unicode strings, the string formatting fails.
Settings the ressource declaration back to simple strings solves the problem.
Downgrading to older versions of js.fullcalendar also solves the problem

**Comment by disko** [comment]
Fixed with latest release.
